DROP TABLE IF EXISTS Promotion;
DROP TABLE IF EXISTS PromotionGroup;

CREATE TABLE IF NOT EXISTS PromotionGroup (
    PromotionGroupID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    StartDate TIMESTAMP NOT NULL,
    EndDate TIMESTAMP NOT NULL,
    SupplierID INTEGER NOT NULL,
    IsActive BOOLEAN DEFAULT 1,
    ExcelFilePath TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SupplierID) REFERENCES Supplier(SupplierID)
);

CREATE TABLE IF NOT EXISTS Promotion (
    PromotionID INTEGER PRIMARY KEY AUTOINCREMENT,
    PromotionGroupID INTEGER NOT NULL,
    ItemID VARCHAR NOT NULL,
    PromoPrice NUMERIC NOT NULL,
    IsActive BOOLEAN DEFAULT 1,
    FOREIGN KEY (PromotionGroupID) REFERENCES PromotionGroup(PromotionGroupID) ON DELETE CASCADE,
    FOREIGN KEY (ItemID) REFERENCES Item(ItemID)
);
